export { default as BazaarBuzzBanner } from "./Bazaar-Buzz banner.png";
export { default as BazaarBuzzHome } from "./Bazaar-Buzz.png";
export { default as BazaarBuzzProducts } from "./Bazaar-Buzz (1).png";
export { default as BazaarBuzzProductDts } from "./Bazaar-Buzz (2).png";
export { default as BazaarBuzzPymentInfo } from "./Bazaar-Buzz (3).png";
export { default as BazaarBuzzPyment } from "./Bazaar-Buzz (4).png";
export { default as cc } from "./HealthPro banner.png";
export { default as HealthProHome } from "./HealthPro.png";
export { default as HealthProBanner } from "./HealthPro banner.png";
export { default as HealthProDoctorDts } from "./HealthPro (1).png";
export { default as HealthProAppointment } from "./HealthPro (2).png";
export { default as HealthProProfile } from "./HealthPro (3).png";
export { default as ParkSpotterMainBanner } from "./ParkSpotter/Parkspotter-banner.png";
export { default as ParkSpotterMainHome } from "./ParkSpotter/Parkspotter-main-home.png";
export { default as ParkSpotterMainRegister } from "./ParkSpotter/Parkspotter-register.png";
export { default as ParkSpotterMainDashboard } from "./ParkSpotter/Parkspotter-main-dashboard.png";
export { default as ParkSpotterMainTicketCreate } from "./ParkSpotter/Parkspotter-main-ticket-create.png";
export { default as ParkSpotterMainAvailableSlots } from "./ParkSpotter/Parkspotter-main-available-slots.png";
export { default as ParkSpotterMainTicketPayment } from "./ParkSpotter/Parkspotter-main-ticket-payment.png";
export { default as ParkSpotterMainEmployeeList } from "./ParkSpotter/Parkspotter-main-employee-list.png";
export { default as ParkSpotterMainEmployeeSelary } from "./ParkSpotter/Parkspotter-main-selary.png";
export { default as ParkSpotterMainZones } from "./ParkSpotter/Parkspotter-main-zones.png";
export { default as ParkSpotterMainLocation } from "./ParkSpotter/Parkspotter-main-location.png";
export { default as ParkSpotterPwa1 } from "./ParkSpotter/Parkspotter-pwa-login.png";
export { default as ParkSpotterPwa2 } from "./ParkSpotter/parkspotter-pwa (1).png";
export { default as ParkSpotterPwa3 } from "./ParkSpotter/parkspotter-pwa (2).png";
export { default as ParkSpotterPwa4 } from "./ParkSpotter/parkspotter-pwa (3).png";
export { default as ParkSpotterPwa5 } from "./ParkSpotter/parkspotter-pwa (4).png";
export { default as ParkSpotterPwa6 } from "./ParkSpotter/parkspotter-pwa (5).png";
export { default as Education1 } from "./education/EDUCATION-banner.png";
export { default as Education2 } from "./education/EDUCATION-home.png";
export { default as Education3 } from "./education/EDUCATION-course.png";
export { default as Education4 } from "./education/EDUCATION-about.png";
export { default as Education5 } from "./education/EDUCATION-contact.png";
export { default as DoctorTeam1 } from "./DoctorTeam/doctor-team (1).png";
export { default as DoctorTeam2 } from "./DoctorTeam/doctor-team (2).png";
export { default as CartCalculate1 } from "./CartCalculate/CartCalculate (1).png";
export { default as CartCalculate2 } from "./CartCalculate/CartCalculate (2).png";
export { default as SearchBooks } from "./SearchBooks/search-book.png";
export { default as MacbookPro1 } from "./MacbookPro/Macbook-Pro (1).png";
export { default as MacbookPro2 } from "./MacbookPro/Macbook-Pro (2).png";
